import type { Metadata } from "next";
import { Oswald,Roboto } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Footer from "@/components/Footer";

const myFont = Oswald({
  weight: "400",
  subsets: ["latin"],
  variable: "--oswald-font"
});

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--roboto-font-family"
});

export const metadata: Metadata = {
  title: "Image Box App",
  description: "Generated by create Image Box app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${myFont.className} ${roboto.variable}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
            <Footer />
            <Toaster position="bottom-center" />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
